CREATE TABLE CLIENTES(
    ID_CLIENTE VARCHAR2(7),
    NOMBRE VARCHAR2(50),
    DNI VARCHAR2(11),
    CORREO_ELECTRONICO VARCHAR(2),
    TELEFONO VARCHAR2(20),
CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE LIBROS(
    ID_LIBRO VARCHAR2(7),
    TITULO VARCHAR2(50),
    AUTOR VARCHAR2(40),
    GENERO VARCHAR2(20),
    AÑO_PUBLICACION DATE,
CONSTRAINT PK_ID_LIBRO PRIMARY KEY (ID_LIBRO)
);

CREATE TABLE ALQUILAN(
    ID_REGISTRO VARCHAR2(7),
    FECHA_REGISTRO DATE,
    ID_CLIENTE VARCHAR2(7),
    ID_LIBRO VARCHAR2(7),
    CONSTRAINT PK_ID_REGISTRO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
    CONSTRAINT FK_ID_LIRBO FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS (ID_LIBRO)
);

DROP TABLE ALQUILAN;
DROP TABLE LIBROS;
DROP TABLE CLIENTES;
