BEGIN 
    INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('1', 'JUAN' , '89456242L' , 'juan@example.com' , '644789554' );
    INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('2','CARLA','56481234K','Carla@example.com','988945662');
   INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('3','CARLOS','87452654Q','Carlos@example.com','123456789');
   INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('4','PAOLA','12356485T','Paola@example.com','655649778');
    INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('5','LUIS','45871265Y','Luis@example.com','976485214');
   INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('6','VICTOR','74326528B','Victor@example.com','976854214');
    INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('7','ANDREA','06879525H','Andrea@example.com','976223355');
  INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('8','MARIA','11114455P','Maria@example.com','976885514');
  INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('9','JORGE','55447862Q','Jorge@example.com','976668895');
  INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, DNI, CORREO_ELECTRONICO,TELEFONO)
    VALUES('10','YOEL','74851654F','Yoel@example.com','976552146');
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
        DBMS_OUTPUT.PUT_LINE('SE DESHACE LAS MODIFICACIONES');
        ROLLBACK;
END;


BEGIN
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('1','QUIJOTE','PEREZ','NOVELA','1999');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('2','Harry','Juan','Ciencia Ficción','2010');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('3','La Dueña','J.K','Terror','2003');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('4','La Perla','J.K','Histórico','2020');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('5','El Camino','Luís','Terror','1998');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('6','Fin del Mundo','Rowling','Ciencia Ficción','1997');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('7','XXI','Rowling','Histórico','2021');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('8','Raza','Xus','Ciencia Ficción','2005');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('9','Tú','Juan','Novela','2006');
    INSERT INTO LIBROS (ID_LIBRO,TITULO,AUTOR,GENERO,AÑO_PUBLICACION)
    VALUES('10','El Armero','Pérez','Novela','2007');
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR EN LA TRANSACCION:'||SQLERRM);
        DBMS_OUTPUT.PUT_LINE('SE DESHACE LAS MODIFICACIONES');
        ROLLBACK;
END;
    